var fs = require('fs')
var path = require('path')
var ip = require('ip').address()
fs.writeFileSync(path.resolve('config.js'), 'var CURRENT_IP = \'' + ip + '\'')
fs.writeFileSync(path.resolve('devConfig.js'), 'export default { CURRENT_IP : \'' + ip + '\'}')
